CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  object_id TEXT NOT NULL,
  email TEXT NOT NULL DEFAULT '',
  display_name TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE (tenant_id, object_id)
);

CREATE TABLE halo_grants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  halo_url TEXT NOT NULL,
  client_id TEXT NOT NULL,
  scope TEXT NOT NULL,
  encrypted_token_json JSONB NOT NULL,
  invalidated_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE sessions (
  session_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE background_sessions (
  background_session_hash TEXT PRIMARY KEY,
  session_hash TEXT NOT NULL REFERENCES sessions(session_hash) ON DELETE CASCADE,
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE bug_report_sessions (
  session_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  diagnostics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  expires_at BIGINT NOT NULL,
  claimed_at BIGINT,
  consumed_at BIGINT,
  created_at BIGINT NOT NULL
);

CREATE TABLE conversation_mappings (
  id TEXT PRIMARY KEY,
  mailbox_email TEXT NOT NULL,
  ticket_id INTEGER NOT NULL,
  ticket_number TEXT NOT NULL,
  conversation_id TEXT NOT NULL DEFAULT '',
  normalized_subject TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE message_mappings (
  mailbox_email TEXT NOT NULL,
  message_id_key TEXT NOT NULL,
  mapping_id TEXT NOT NULL REFERENCES conversation_mappings(id) ON DELETE CASCADE,
  created_at BIGINT NOT NULL,
  PRIMARY KEY (mailbox_email, message_id_key)
);

CREATE TABLE inline_image_cache (
  halo_tenant TEXT NOT NULL,
  sha256 TEXT NOT NULL,
  halo_attachment_id TEXT NOT NULL,
  renderable_url TEXT NOT NULL,
  media_type TEXT NOT NULL,
  byte_length INTEGER NOT NULL,
  filename TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  last_used_at BIGINT NOT NULL,
  usage_count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (halo_tenant, sha256)
);

CREATE TABLE compose_inline_image_prefetch (
  prefetch_key TEXT PRIMARY KEY,
  compose_operation_id TEXT NOT NULL,
  attachment_fingerprint TEXT NOT NULL,
  cid_hash_json JSONB NOT NULL,
  halo_tenant TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE email_attachment_prefetch (
  prefetch_key TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  halo_tenant TEXT NOT NULL,
  ticket_id INTEGER NOT NULL,
  operation_id TEXT NOT NULL,
  attachment_fingerprint TEXT NOT NULL,
  expected_count INTEGER NOT NULL,
  expected_bytes INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  expires_at BIGINT NOT NULL,
  consumed_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE (user_id, operation_id, halo_tenant, ticket_id)
);

CREATE TABLE email_attachment_prefetch_items (
  prefetch_key TEXT NOT NULL REFERENCES email_attachment_prefetch(prefetch_key) ON DELETE CASCADE,
  attachment_key TEXT NOT NULL,
  filename TEXT NOT NULL,
  content_type TEXT NOT NULL,
  attachment_type TEXT NOT NULL,
  reported_size INTEGER NOT NULL,
  decoded_size INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending',
  halo_attachment_id TEXT,
  halo_filename TEXT NOT NULL DEFAULT '',
  halo_filesize INTEGER NOT NULL DEFAULT 0,
  halo_type INTEGER NOT NULL DEFAULT 0,
  show_for_users BOOLEAN NOT NULL DEFAULT TRUE,
  failure_code TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (prefetch_key, attachment_key)
);

CREATE TABLE ticket_creation_metadata_cache (
  cache_key TEXT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  halo_tenant TEXT NOT NULL,
  payload_json JSONB NOT NULL,
  fetched_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (cache_key, user_id, halo_tenant)
);

CREATE TABLE ticket_creation_intents (
  operation_id TEXT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  halo_tenant TEXT NOT NULL,
  encrypted_intent_json JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  ticket_id INTEGER,
  ticket_number TEXT NOT NULL DEFAULT '',
  action_id TEXT NOT NULL DEFAULT '',
  last_error TEXT NOT NULL DEFAULT '',
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (operation_id, user_id, halo_tenant)
);

CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX idx_background_sessions_expires_at ON background_sessions(expires_at);
CREATE INDEX idx_bug_report_sessions_expires_at ON bug_report_sessions(expires_at);
CREATE INDEX idx_conversation_mappings_conversation
  ON conversation_mappings(mailbox_email, conversation_id);
CREATE INDEX idx_message_mappings_mapping_id ON message_mappings(mapping_id);
CREATE INDEX idx_inline_image_cache_last_used ON inline_image_cache(last_used_at);
CREATE INDEX idx_compose_inline_image_prefetch_expires
  ON compose_inline_image_prefetch(expires_at);
CREATE INDEX idx_email_attachment_prefetch_expires
  ON email_attachment_prefetch(status, expires_at);
CREATE INDEX idx_email_attachment_prefetch_items_status
  ON email_attachment_prefetch_items(prefetch_key, status);
CREATE INDEX idx_ticket_creation_metadata_expires
  ON ticket_creation_metadata_cache(expires_at);
CREATE INDEX idx_ticket_creation_intents_expires ON ticket_creation_intents(expires_at);
